### ISSUE TITLE
README Language

### ISSUE THREAD

**Issue by VrushM** [simoncos/zhihu-analysis-python#5]
Subject : Can we have a README file in English
 
Hey hie, The project you uploaded seems interesting and I would love to contribute to it. So can we have a README in English language so that It will be easy for everyone to have a look at it.

Thanks in advance :)

**Comment by simoncos** [comment]
Hi @VrushM, glad to hear that you're interested in this project. Let me first do a short introduction. This project aims to do some social network analysis on a Chinese Q&A forum called Zhihu. It mainly involves two parts: data crawling and data analysis. We have both report and slides in English for more details
[here](https://github.com/simoncos/zhihu-analysis-python/tree/master/analysis-report). 

As for contribution, now the biggest problem is that our crawler has been totally broken as Zhihu keeps upgrading its website, so we cannot get more data for analysis, which is the main topic written in current Readme. If you'd like to participate, maybe you can first take a look at this part. Or we can discuss further if you're more into the analysis part or something.

**Comment by VrushM** [comment]
Sure , will have a look at it and will let you know. Thanks @simoncos
